blog/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='blog'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('detail/<slug:slug>', views.Detail.as_view(), name='post')
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smallblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.

STATUS = (
    (0, 'Draft'),
    (1, 'Publish')
)

class Post(models.Model):
    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField()
    abstract = models.CharField(max_length=255, help_text="Tóm tắt cơ bản về bài viết")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    updated_at = models.DateTimeField(auto_now=True)
    content = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    category = models.ForeignKey('blog.Category', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title
    
    def __unicode__(self):
       return '%s' % self.title
    
    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)
    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'slug': self.slug})
    

class Category(models.Model):
    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)

    def __unicode__(self):
       return '%s' % self.title

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

blog/views.py
from django.shortcuts import render
from django.views import View
from .models import Category, Post
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

# Create your views here.
class Index(View):
    def get(self, request):
        categories = Category.objects.all()
        posts = Post.objects.filter(status=1).order_by('created_at')
        paginator = Paginator(posts, 2)

        page = request.GET.get('page')
        try:
            posts = paginator.get_page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmtyPage:
            posts = paginator.page(paginator.num_pages)

        data = {'posts': posts}
        return render(request, 'blog/index.html', data)

class Detail(View):
    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        return render(request, 'blog/detail.html', {'post': post})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}

        {% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/css/styles.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'blog/favicon/favicon.ico' %}"/>
    <link rel="icon" href="{% static 'blog/favicon/favicon.ico' %}" type="image/x-icon">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

</head>

<body>
    <nav class="shadow sticky-top navbar navbar-expand-sm navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'blog:index' %}"><img style="width: 25px" src="{% static 'blog/favicon/favicon.ico' %}"></img></a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">About</a>
                </li>
                {% comment %} <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownId">
                            <a class="dropdown-item" href="#">Action 1</a>
                            <a class="dropdown-item" href="#">Action 2</a>
                        </div>
                    </li> {% endcomment %}
            </ul>
            {% block sayhello %}
            
            {% endblock sayhello %}
            


        </div>
    </nav>


    <div class="container" id="container">
        {% block quote %}
        {% endblock %}
        <!-- Content -->
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-8">
                {% block content %}

                {% endblock content %}
                {% block form %}
                
                {% endblock form %}
                <div class="row">
                    <div class="col-sm-12 text-center">
                        {% block pagination %}
                    
                        {% endblock pagination %}
                    </div>
                    
                </div>
            </div>
            <!-- Slide bar -->
            <div class="col-sm-12 col-md-12 col-lg-4 mt-2">
                <div class="sidebar-module sidebar-module-inset border shadow custom margin-sidebar">
                    <h4>Comming soon...!</h4>
                    <div>
                        <!-- <img class="avatar mx-auto d-block border shadow" src="{% static 'blog/icons/github.svg' %}" alt=""> -->
                        <!-- <p>Comming soon...!</p> -->
                    </div>

                </div>
                <!-- <div class="sidebar-module border shadow custom margin-sidebar">
                    {% block lienquan %}
                    
                    {% endblock lienquan %}
                </div> -->
                <!-- <div class="sidebar-module border shadow custom margin-sidebar">
                    <h4>Liên hệ</h4>
                    <ol class="list-unstyled">
                        <li><a href="https://github.com/zumianax"><img class="icon"
                                    src="{% static 'blog/icons/github.svg' %}" alt="">GitHub</a></li>
                        <li><a href="https://facebook.com/vuongle1998"><img class="icon"
                                    src="{% static 'blog/icons/facebook.png' %}" alt="">Facebook</a></li>
                        <li><a href="https://instagram.com/vuongle1998"><img class="icon"
                                    src="{% static 'blog/icons/instagram.png' %}" alt="">Instagram</a></li>
                    </ol>
                </div> -->

            </div>
            <!-- End slide bar -->

        </div>
    </div>
    <footer class="mt-2 page-footer font-small cyan darken-3">
        <div class="footer-copyright text-center py-3">
            Vuong Le 2019
        </div>
    </footer>
    
    {% block scripts %}
    
    {% endblock scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

</body>

</html>

blog/templates/blog/detail.html
{% extends "blog/base.html" %}

{% block title %}
    {{ post.title }}
{% endblock title %}

{% block content %}


<div class="row">
    <div class="col-sm-12">
        <div class="border rounded shadow custom margin">
            <div class="text-center">
                <img style="width: 100%" class="img-fluid" src="{{ post.image.url }}" alt="{{ post.image }}">
                {% comment %} <div class="caption">Hình gì đó đang ở đây</div> {% endcomment %}
            </div>

            <a href="{% url 'blog:post' post.slug %}">
                <h3 class="title">{{ post.title }}</h3>
            </a>
            
            <small>{{ post.category }} - {{ post.author }} - {{ post.created_at|date:'d-m-y h:i' }}</small>
            
            
            <hr>
            <p class="content">{{ post.content | safe }}</p>
        </div>
    </div>
</div>

{% endblock content %}

<!-- {% block lienquan %}
    <h4>Bài liên quan</h4>
    <div class="container">
        
    </div>
{% endblock lienquan %}  -->

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}
Home
{% endblock title %}

{% block quote %}
<div class="shadow border rounded">
    <div class="container">
        <h2 class="display-5">Comming soon...!</h2>
        <p>...</p>
    </div>
</div>
<hr>
{% endblock %}



{% block content %}

<div class="row">
    {% if posts %}
    
        {% for post in posts %}
        <div class="col-sm-12 col-md-12">
            <div class="thumbnail border rounded shadow">
                <img src="{{ post.image.url }}" alt="{{ post.image }}">
                <div class="caption mt-4">
                    <a href="{% url 'blog:post' post.slug %}" class="">
                        <h4 class="tilte">{{ post.title }}</h4>
                        
                    </a>
                    <small>{{ post.author }} - {{ post.created_at|date:'d-m-y h:i' }}</small>
                    <!-- {{ post.created_at|date:'d-m-Y' }} -->
                    <hr>

                    <p class="margin">
                        {{ post.abstract| safe }} ...
                        <!-- {{ post.abstract| safe| truncatewords:"10" }} -->
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    {% endif %}
</div>
<!-- End content -->

{% endblock content %}

{% block pagination %}
<div class="row">
    <div class="col-sm-12 col-md-12 margin">
        <span class="">
            {% if posts.has_previous %}
                <a class="" href="?page=1">&laquo;First </a>
                <a href="?page={{ posts.previous_page_number }}">Previous </a>
            {% endif %}
        </span>
        <span class="active">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }} 
        </span> 
        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">Next </a>
            <a href="?page={{ posts.paginator.num_pages }}"> Last &raquo;</a>    
        {% endif %}
    </div>
</div>


{% comment %} {% if posts.has_other_pages %}
  <ul class="pagination">
    {% if posts.has_previous %}
      <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in posts.paginator.page_range %}
      {% if posts.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if posts.has_next %}
      <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %} {% endcomment %}


{% endblock pagination %}



<!-- {% block lienquan %}
    <h4>Bài liên quan</h4>
    <div class="container">
        
    </div>
{% endblock lienquan %} -->